version: "2"
services:
  neutron-db2data:
    image: cwds/cals_db2_data:latest
    privileged: true
    ports:
      - "51000:50000"
    environment:
      - DB2INST1_PASSWORD=db2inst1
      - LICENSE=accept
    networks:
      - neutronnet
  neutron-postgresql_data:
    image: cwds/postgresql_data
    networks:
      - neutronnet
    ports:
      - "5432:5432"
networks:
  neutronnet:


