batchSize: 500
elasticSearchBulkSize: 500
readerThreadsCount: 1

elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}

elasticsearch.additional.nodes:
  - localhost:9300
  - localhost:9300

elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-facilities}
elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-facility}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

lisDataSourceFactory:
  properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.connection.username: ${DB_LIS_USER:-postgres_data}
      hibernate.connection.password: ${DB_LIS_PASSWORD:-postgres_data}
      hibernate.connection.url: ${DB_LIS_JDBC_URL:-jdbc:postgresql://192.168.99.100:5432/?currentSchema=lis}
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.c3p0.min_size: 5
      hibernate.c3p0.max_size: 5

fasDataSourceFactory:
  properties:
      hibernate.default_schema: ${DB_FAS_DEFAULT_SCHEMA:-fas}
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.connection.username: ${DB_FAS_USER:-postgres_data}
      hibernate.connection.password: ${DB_FAS_PASSWORD:-postgres_data}
      hibernate.connection.url: ${DB_FAS_JDBC_URL:-jdbc:postgresql://192.168.99.100:5432/?currentSchema=fas}
      hibernate.show_sql: false
      hibernate.c3p0.min_size: 5
      hibernate.c3p0.max_size: 5
