batchSize: 100
elasticSearchBulkSize: 100
readerThreadsCount: 10

elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}

elasticsearch.additional.nodes:
  - localhost:9300
  - localhost:9300

elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-facilities}
elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-facility}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

cmsDataSourceFactory:
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: com.ibm.db2.jcc.DB2Driver
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_CMS_USER:-db2inst1}
      hibernate.connection.password: ${DB_CMS_PASSWORD:-db2inst1-pwd}
      hibernate.connection.url: ${DB_CMS_JDBC_URL:-jdbc:db2://192.168.99.100:50000/DB0TDEV}
      hibernate.default_schema: ${DB_CMS_SCHEMA:-CWSCMSRS}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.c3p0.min_size: 5
      hibernate.c3p0.max_size: 5
