batchSize: 50000
elasticSearchBulkSize: 50000
readerThreadsCount: 10

elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}

elasticsearch.additional.nodes:
  - localhost:9300
  - localhost:9300

elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-facilities}
elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-facility}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

cmsDataSourceFactory:
  properties:
      hibernate.dialect: gov.ca.cwds.jobs.cals.facility.cws.CustomDb2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: com.ibm.db2.jcc.DB2Driver
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_CMS_USER:-db2inst1}
      hibernate.connection.password: ${DB_CMS_PASSWORD:-db2inst1-pwd}
      hibernate.connection.url: ${DB_CMS_JDBC_URL:-jdbc:db2://192.168.99.100:50000/DB0TDEV}
      hibernate.default_schema: ${DB_CMS_SCHEMA:-CWSCMSRS}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.c3p0.min_size: 5
      hibernate.c3p0.max_size: 5

calsnsDataSourceFactory:
  properties:
      hibernate.dialect: gov.ca.cwds.cals.persistence.hibernate.dialect.JsonbSupportPostgreSQL9Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_NS_USER:-postgres_data}
      hibernate.connection.password: ${DB_NS_PASSWORD:-postgres_data}
      hibernate.connection.url: ${DB_NS_JDBC_URL:-jdbc:postgresql://192.168.99.100:5432/postgres_data}
      hibernate.default_schema: ${DB_NS_DEFAULT_SCHEMA:-calsns}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true
      hibernate.c3p0.min_size: 5
      hibernate.c3p0.max_size: 5
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_query_cache: true
      hibernate.connection.autocommit: false
