elasticsearch.host: localhost
elasticsearch.port: 9300
elasticsearch.cluster: elasticsearch
elasticsearch.alias: facilities
elasticsearch.doctype: facility

job.lis.reader.query: select
                            f.fac_nbr as "id",
                            ft.tbl_fac_type_desc as "type",
                            f.fac_name as "name",
                            f.fac_licensee_name as "licensee_name",
                            f.fac_do_eval_code as "assigned_worker",
                            dc.do_name as "district_office",
                            f.fac_nbr as "license_number",

                            f.fac_mail_street_addr as "mail_street_address",
                            f.fac_mail_city as "mail_city",
                            f.fac_mail_state as "state_code_type",
                            f.fac_mail_zip_code as "zip_code",
                            '' as street_number,
                            '' as zip_suffix_code,

                            f.fac_res_street_addr as "residential_street_address",
                            f.fac_res_city as "residential_city",
                            f.fac_res_state as "residential_state",
                            f.fac_res_zip_code as "residential_zip",

                            co.tbl_co_desc as "county",
                            f.fac_phone_nbr as "primary_phone_number",
                            '' as "alt_phone_number",
                            fs.tbl_fac_status_desc as "status",
                            '' as "license_status",
                            '' as "street_name",

                            f.fac_licensee_type as "licensee_type",
                            f.fac_lic_eff_date as "license_effective_date",
                            f.fac_last_visit_date as "last_visit_date",
                            f.fac_last_visit_reason as "last_visit_reason",
                            f.fac_email_address as "email_address",
                            f.fac_capacity as "capacity",
                            f.fac_orig_appl_rec_date as "original_application_received_date"
                          from
                            lis_fac_file f,
                            lis_do_file dc,
                            lis_table_file ft,
                            lis_table_file fs,
                            lis_table_file co
                          where f.fac_do_nbr = dc.do_nbr
                                and f.fac_type = ft.TBL_FAC_TYPE_CODE
                                and ft.TBL_FAC_TYPE_CODE is not null
                                and f.fac_status = fs.tbl_fac_status_code
                                and fs.tbl_fac_status_code is not null
                                and f.fac_co_nbr = co.tbl_co_nbr
                                and co.tbl_co_nbr is not null;