batchSize: 1000
elasticSearchBulkSize: 300
readerThreadsCount: 10

elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}

elasticsearch.additional.nodes:
  - localhost:9300
  - localhost:9300
                     
elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
elasticsearch.alias: ${ELASTIC_SEARCH_ALIAS:-facilities}
elasticsearch.doctype: ${ELASTIC_SEARCH_DOCTYPE:-facility}
#
elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

lisDataSourceFactory:
  properties:
      hibernate.dialect: gov.ca.cwds.cals.persistence.hibernate.dialect.CONNXDialect
      hibernate.show_sql: true
      hibernate.default_catalog: ${DB_LIS_CATALOG:-hwdcs1_cahwnet_gov}
      hibernate.default_schema: ${DB_LIS_SCHEMA:-dbo}
      hibernate.connection.autocommit: false

      hibernate.dialect: gov.ca.cwds.cals.persistence.hibernate.dialect.CONNXDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: com.Connx.jdbc.TCJdbc.TCJdbcDriver
      hibernate.connection.username: ${DB_LIS_USER:-CWDS_Admin}
      hibernate.connection.password: ${DB_LIS_PASSWORD:-x}
      hibernate.connection.url: ${DB_LIS_JDBC_URL:-jdbc:connx:DD=CX_All;Gateway=10.211.5.29;port=7502}
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: false

fasDataSourceFactory:
  properties:
      hibernate.default_schema: ${DB_FAS_DEFAULT_SCHEMA:-fas}
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.connection.username: ${DB_FAS_USER:-postgres_data}
      hibernate.connection.password: ${DB_FAS_PASSWORD:-postgres_data}
      hibernate.connection.url: ${DB_FAS_JDBC_URL:-jdbc:postgresql://192.168.99.100:5432/postgres_data}
      hibernate.show_sql: false

cmsDataSourceFactory:
  properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: com.ibm.db2.jcc.DB2Driver
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      hibernate.connection.username: ${DB_CMS_USER:-db2inst1}
      hibernate.connection.password: ${DB_CMS_PASSWORD:-db2inst1-pwd}
      hibernate.connection.url: ${DB_CMS_JDBC_URL:-jdbc:db2://192.168.99.100:32768/DB0TDEV}
      hibernate.default_schema: ${DB_CMS_SCHEMA:-CWSCMSRS}
      hibernate.connection.connectionTimeout: 1000000
      hibernate.connection.loginTimeout: 1000000
      hibernate.connection.keepAliveTimeOut: 8
      hibernate.jdbc.time_zone: America/Los_Angeles
      hibernate.jdbc.use_scrollable_resultset: true

calsnsDataSourceFactory:
  properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.connection.driver_class: org.postgresql.Driver
      hibernate.connection.username: ${DB_NS_USER:-postgres_data}
      hibernate.connection.password: ${DB_NS_PASSWORD:-postgres_data}
      hibernate.connection.url: ${DB_NS_JDBC_URL:-jdbc:postgresql://192.168.99.100:32770/?currentSchema=calsns}
      hibernate.show_sql: false
